version: 2

models:

  - name: fact_orders
    description:  Contains order details such as order id, shipping & tracking details and estimated delivery. Combined Promos dimension to orders so we have promotions details on each order.

  - name: dim_products
    description: Contains products we sell and inventory information
    columns:
      - name: product_id
        description: product_id is the primary key for the prodct table

  - name: dim_users
    description: Contains user details; user id and user contact information. Denormalized users and addresses table to give a full picture of a user.
    columns:
      - name: user_id
        description: user_id is the primary key for the users table

  - name: fact_user_order
    description: contains order information at the user level. Aggregate order data at user level so we can perform user order analaysis.
    columns:
      - name: user_id
        description: user_id is the primary key for the users table
  - name: int_events
    description: contains event information,intermediate table used for fact_page_views fact.
    columns:
      - name: event_id
        description: event_id is the primary key for the users table

  - name: fact_page_views 
    description: contains all page view events from greenery's events data. Combined user and product information at event level so we have one big table for event analysis.
    columns:
      - name: event_id
      
  - name: fact_products
    description: contains product leve fact metrics. This model helps answer product's conversion rate question.
    columns:
      - name: session_id
        description: event_id is the primary key for the users table
        
  - name: int_session_agg 
    description: Contains aggregate level session events to calculate overall conversion level metrics
    columns:
      - name: event_id
        description: event_id is the primary key for the users table
